[client]
showErrorDetails = true
toolbarMode = "auto"
showSidebarNavigation = false

[theme]
base = "light"
primaryColor = "#FF4B4B"
backgroundColor = "#8a9090"
secondaryBackgroundColor = "#dbdce0"
textColor = "#000000"
font = "sans serif"
